=== AlexAndriamahaleo/MasterAixMarseilleUniversite/MasterAMU/masterinfo.univ-mrs.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ENTITY dom.amu        "univ-amu.fr">
<!ENTITY dom.mrs        "univ-mrs.fr">
<!ENTITY dom.lif        "lif.&dom.mrs;">
<!ENTITY dom.luminy     "luminy.&dom.amu;">
<!ENTITY dom.perso      "perso.&dom.luminy;">
<!ENTITY pageperso.lif  "pageperso.&dom.lif;">

<!ENTITY stj            "Saint Jérôme">
<!ENTITY lum            "Luminy">

<!ENTITY % obligatoire  "obligatoire">
<!ENTITY % option       "option">
<!ENTITY % bonus        "bonus">

<!ENTITY % paragraph    "#PCDATA | b | strong | i | a | u | ul | ol | table">

<!ELEMENT master                (table-intervenants,unites,parcours,specialite+)>
<!ELEMENT unites                (ue+)>
<!ELEMENT table-intervenants    (intervenant+)>
<!ELEMENT intervenant           (nom,tel?,mail+,site-perso*)>
<!ATTLIST intervenant
        id  ID  #REQUIRED
        >
<!ELEMENT list-intervenants     (ref-intervenant+)>
<!ELEMENT ue                    (nom,credits,description?,plan?,list-lieu?,list-intervenants?)>
<!ATTLIST ue
        id  ID  #REQUIRED
        role  (%obligatoire;|%option;|%bonus;)  #REQUIRED
        >
<!ELEMENT parcours              (nom,description,semestre+,list-intervenants,list-débouchés?)>
<!ATTLIST parcours
        code ID    #REQUIRED
        >
<!ELEMENT specialite            (nom?,description?,parcours+)>
<!ATTLIST specialite
        id  ID  #REQUIRED
        >
<!ELEMENT list-ue               (ref-ue)+>
<!ELEMENT ref-ue                EMPTY>
<!ATTLIST ref-ue
        ref IDREF #REQUIRED
        >
<!ELEMENT list-lieu             (lieu-ens+)>
<!ELEMENT ref-intervenant   EMPTY>
<!ATTLIST ref-intervenant
        ref  IDREF #REQUIRED
        >
<!ELEMENT semestre              (list-ue+)>
<!ATTLIST semestre
        id  ID    #REQUIRED
        ref CDATA #IMPLIED   <!-- Pas required ? -->
        >
<!ELEMENT list-débouchés        (métier+)>
<!ELEMENT table             (tr)+>
<!ELEMENT tr                (th|td)+>
<!ELEMENT description       (%paragraph; | p)*>
<!ELEMENT métier            (#PCDATA)>
<!ELEMENT nom               (#PCDATA)>
<!ELEMENT tel               (#PCDATA)>
<!ELEMENT mail              (#PCDATA)>
<!ELEMENT site-perso        (#PCDATA)>
<!ELEMENT credits           (#PCDATA)>
<!ELEMENT plan              (#PCDATA)>
<!ELEMENT lieu-ens          (#PCDATA)>
<!ELEMENT diplôme           (#PCDATA)>
<!ELEMENT salaire           (#PCDATA)>

<!ELEMENT p                 ( %paragraph; )*>
<!ELEMENT b                 (#PCDATA)>
<!ELEMENT strong            (#PCDATA)>
<!ELEMENT i                 (#PCDATA)>
<!ELEMENT a                 (#PCDATA)>
<!ATTLIST a
        href  CDATA  "#"
        >
<!ELEMENT u                 (#PCDATA)>
<!ELEMENT ul                (li+)>
<!ELEMENT ol                (li+)>
<!ELEMENT li                (#PCDATA)>
<!ELEMENT th                (#PCDATA)>
<!ELEMENT td                (#PCDATA)>

=== AlexAndriamahaleo/MasterAixMarseilleUniversite/MasterAMU/masterinfo.univ-mrs.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE master SYSTEM "masterinfo.univ-mrs.dtd">

<master>
    <table-intervenants>
        <intervenant id="arrighi">
            <nom>Pablo ARRIGHI</nom>
            <mail>pablo.arrighi@&dom.amu;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~pablo.arrighi/</site-perso>
        </intervenant>
        <intervenant id="boucelma">
            <nom>Omar BOUCELMA</nom>
            <mail>omar.boucelma@&dom.amu;</mail>
        </intervenant>
        <intervenant id="chepoi">
            <nom>Victor CHEPOI</nom>
            <mail>victor.chepoi@&dom.amu;</mail>
            <site-perso>https://pageperso.lif.univ-mrs.fr/~victor.chepoi/</site-perso>
        </intervenant>
        <intervenant id="contensin">
            <nom>Magali CONTENSIN</nom>
            <mail>magali.contensin@&dom.amu;</mail>
        </intervenant>
        <intervenant id="coady">
            <nom>Ann COADY</nom>
            <mail>anne.coady@&dom.amu;</mail>
        </intervenant>
        <intervenant id="creignou">
            <nom>Nadia CREIGNOU</nom>
            <mail>nadia.creignou@&dom.lif;</mail>
            <site-perso>http://www.lif.univ-mrs.fr/annuaire/personne/1155937</site-perso>
        </intervenant>
        <intervenant id="denis">
            <nom>Francois DENIS</nom>
            <mail>francoi.denis@&dom.lif;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~francois.denis/</site-perso>
        </intervenant>
        <intervenant id="favre">
            <nom>Benoit FAVRE</nom>
            <mail>benoit.favre@&dom.amu;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~benoit.favre/</site-perso>
        </intervenant>
        <intervenant id="godard">
            <nom>Emmanuel GODARD</nom>
            <mail>emmanel.godard@&dom.lif;</mail>
            <site-perso>http://www.lif.univ-mrs.fr/~egodard</site-perso>
        </intervenant>
        <intervenant id="habet">
            <nom>Djamal HABET</nom>
            <mail>djamal.habet@&dom.amu;</mail>
            <mail>djamal.habet@lis-lab.fr</mail>
            <site-perso>http://www.lsis.org/habetd/</site-perso>
        </intervenant>
        <intervenant id="jamet">
            <nom>Line JAMET-JAKUBIEC</nom>
            <mail>line.jametjakubiec@&dom.lif;</mail>
            <site-perso>http://www.dil.univ-mrs.fr/~jakubiec/</site-perso>
        </intervenant>
        <intervenant id="labourel">
            <nom>Arnaud LABOUREL</nom>
            <mail>arnaud.labourel@&dom.lif;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~arnaud.labourel/</site-perso>
        </intervenant>
        <intervenant id="massat">
            <nom>Jean Luc MASSAT</nom>
            <mail>jeanlus.massat@&dom.lif;</mail>
            <site-perso>http://jean-luc.massat.perso.luminy.univ-amu.fr/ens/</site-perso>
        </intervenant>
        <intervenant id="niebert">
            <nom>Peter NIEBERT</nom>
            <mail>peter.niebert@&dom.amu;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~peter.niebert/</site-perso>
        </intervenant>
        <intervenant id="morin">
            <nom>Remi MORIN</nom>
            <mail>remi.morin@&dom.lif;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~remi.morin/</site-perso>
        </intervenant>
        <intervenant id="novelli">
            <nom>Noel NOVELLI</nom>
            <mail>noel.novelli@&dom.lif;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~noel.novelli/</site-perso>
        </intervenant>
        <intervenant id="olive">
            <nom>Frederic OLIVE</nom>
            <mail>fredric.olive@&dom.amu;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~frederic.olive/</site-perso>
        </intervenant>
        <intervenant id="perrot">
            <nom>Kevin PERROT</nom>
            <mail>kevin.perrot@&dom.mrs;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~kevin.perrot/</site-perso>
        </intervenant>
        <intervenant id="rene">
            <nom>Lydie RENE CHABAROT</nom>
            <mail>lydie.renechabarot@&dom.amu;</mail>
        </intervenant>
        <intervenant id="sabatier">
            <nom>Claude SABATIER</nom>
            <mail>claude.sabatier@&dom.lif;</mail>
        </intervenant>
        <intervenant id="santocanale">
            <nom>Luigi SANTOCANALE</nom>
            <mail>luigi.santocanale@&dom.amu;</mail>
            <site-perso>http://pageperso.lif.univ-mrs.fr/~luigi.santocanale/</site-perso>
        </intervenant>
        <intervenant id="sellami">
            <nom>Sana SELLAMI</nom>
            <mail>sana.sellami@lis-lab.org</mail>
            <site-perso>http://www.lsis.org/sellamis/</site-perso>
        </intervenant>
    </table-intervenants>
    <parcours code="M1" spec="Tron commun">
        <nom>Master 1 Informatique</nom>
        <description>
            L'objectif de cette première année est de donner les bases indispensables permettant,
            en deuxième année, de choisir une spécialisation dans un domaine précis.
            Sur les 60 crédits de cette première année, 15 crédits correspondent à des enseignements optionnels.
            Ces options permettent de construire un parcours adapté.
            Un choix entre stage ou projet encadré est également proposé au semestre de printemps.
        </description>
        <semestre id="M1S1" ref="S1">
            <list-ue>
                <ue id="ENSINAU1" role="obligatoire">
                    <nom>Génie Logiciel</nom>
                    <credits>6</credits>
                    <description>
                        <ul>
                            <li>Processus logiciel</li>
                            <li>Gestion de projet</li>
                            <li>Spécification et conception (artefact : notation UML)</li>
                            <li>Design patterns</li>
                        </ul>
                    </description>
                    <plan>20h CM, 20h TD, 20h TP</plan>
                    <list-lieu>
                        <lieu-ens>&stj;</lieu-ens>
                        <lieu-ens>&lum;</lieu-ens>
                    </list-lieu>
                    <list-intervenants>
                        <ref-intervenant ref="arrighi"/>
                        <ref-intervenant ref="perrot"/>
                    </list-intervenants>
                </ue>
                <ue id="ENSINAU2" role="obligatoire">
                    <nom>Complexité</nom>
                    <credits>6</credits>
                    <description>
                        Rappels sur les notions d'analyse de la complexité des algorithmes et des problèmes.
                        Notion de problèmes (décision, recherche, dénombrement, énumération, optimisation). Bornes inférieures de complexité.
                        Classes P et NP. Problèmes NP-complets.
                        Méthodes de résolution des problèmes NP-Complets.
                    </description>
                    <plan>20h CM, 20h TD, 20h TP</plan>
                    <list-lieu>
                        <lieu-ens>&stj;</lieu-ens>
                        <lieu-ens>&lum;</lieu-ens>
                    </list-lieu>
                    <list-intervenants>
                        <ref-intervenant ref="creignou"/>
                        <ref-intervenant ref="olive"/>
                    </list-intervenants>
                </ue>
                <ue id="ENSINAU3" role="obligatoire">
                    <nom>Réseaux</nom>
                    <credits>6</credits>
                    <description>
                        Architecture en couches, standard OSI
                        Couche physique
                        Couche liaison de Données
                        Réseau IP
                        Algorithmes de routage, routage IP
                        Protocole TCP/IP
                        Couche Application : HTTP, SMTP, FTP, ...
                        Bases des protocoles cryptographiques (terminologie, architecture à clef publique).
                        Introduction à la Sécurité des réseaux.
                    </description>
                    <plan>20h CM, 20h TD, 20h TP</plan>
                    <list-lieu>
                        <lieu-ens>&stj;</lieu-ens>
                        <lieu-ens>&lum;</lieu-ens>
                    </list-lieu>
                    <list-intervenants>
                        <ref-intervenant ref="godard"/>
                    </list-intervenants>
                </ue>
                <ue id="ENSINAU12" role="obligatoire">
                    <nom>BDR : approfondissement </nom>
                    <credits>3</credits>
                    <description>
                        nous sommes désolé, mais nous n'avons pas encore de résumé.
                    </description>
                    <plan>10h CM, 10h TD, 10h TP</plan>
                    <list-lieu>
                        <lieu-ens>&stj;</lieu-ens>
                        <lieu-ens>&lum;</lieu-ens>
                    </list-lieu>
                    <list-intervenants>
                        <ref-intervenant ref="novelli"/>
                    </list-intervenants>
                </ue>
                <ue id="ENSINAU4" role="obligatoire">
                    <nom>Programmation fonctionnelle</nom>
                    <credits>3</credits>
                    <description>
                        <ol>
                            <li>Introduction à la programmation fonctionnelle, sur l'exemple du langage
                                OCaml
                                Expressions, évaluation, types de base. Polymorphisme, ordre supérieur.
                                Fonctions récursives, filtrage. Les diverses stratégies d'évaluation, application à la
                                programmation d'un opérateur de point fixe.
                            </li>
